### ISSUE TITLE
As a developer I'd like to know more about consuming git (and logs)

### ISSUE THREAD

**Issue by andrew-howden** [littlemanco/www.littleman.co#27]
There are a series of articles about "how to write git logs". However, they don't really go into reason as to why git logs need to be written in that way. 

There are various ways to consume the parts of git; 

- git log
- git lola
- git log --patch
- git log -S
- git blame

As well as 

- PHPStorm annotations
- GitHub Blame

All of which are super useful -- if the participant has followed git conventions

I'd expect this documentation to be in the form of an article.

**Comment by andrew-howden** [comment]
1. We have a bug
2. We need to understand how bug got introduced
3. Bugs are usually introduced as things changed, and due to differing models of how the software should work. So, examining changes can be illustrative to point to bugs
4. Annotate → show patch

This justifies good shortlog, description, justification etc.

It also means git is a mechanism to understand a codebase; given this, we need to be clear on **why**, we're making a particular change, as well as what constrains we're under when making it.

Software is not simply code; it's code made in an environment, and under constraints. When designing it, we need to understand all of the above.

**Comment by andrew-howden** [comment]
We are looking to understand all references to ${X} function. So we run `git log -S${FUNCTION} --patch`. That tells us who edited it and why, and shows the story over time.

**Comment by andrew-howden** [comment]
(If you're similar to me and learning how stuff works in project) a useful git feature is the "pickaxe":

```git log -S 'XX' --patch```

It finds any occurrence of XX in the previous patchsets and shows the log. You can use `--patch` to show the changes made and see how a previous person did a thing (And presumably how we should do it in future)

**Comment by andrewhowdencom** [comment]
Should do this something like:

1. "I need to ${X}" (make these concrete stories)
2. "Here's how to ${X}"
3. "Here's how to maximize the utility of ${X} while writing a commit"

**Comment by andrew-howden** [comment]
`git add --patch`
