### ISSUE TITLE
As a user I'd like to know more about the tradeoffs when creating a CI/CD pipeline

### ISSUE THREAD

**Issue by andrew-howden** [littlemanco/www.littleman.co#37]
1. What a CI/CD system, and historical context thereof
2. The expectations of a CI/CD system, with a goal of improving its utility to team members
3. Splitting the concerns of CI/CD out into components such that each component has a single domain of expertise, and can adopt tooling therein. The domains are:

a. Application compilation
b. Testing
c. CI / Release. Containers that supply tools, invoke them via task runner.
d. Release management (helm, et al)

4. Things that change as a result of "good CI"

should include some notion of what to optimize for in each domain, and their "apis".

I'd expect this documentation to be in the form of an article

**Comment by andrew-howden** [comment]
Burden of proof: Increase development velocity. This change should:

Increase the number of releases
Increase the number of people who release
Increase the realiability of releases
Increase the number of changes to the build pipeline
Decrease the number of total jobs
Increase build speed
Allow simpler, more reliable rollback
Allow simpler build configuration

**Comment by andrew-howden** [comment]
foop

**Comment by andrew-howden** [comment]
"Large Configuration"; a smell. Should be split among the various tools.

**Comment by andrew-howden** [comment]
"Accessibility & Integration with tooling". Things like version control. Should start from first principles of expectations, and then make the case for integrating with VCS via PR.

**Comment by andrew-howden** [comment]
Allow developers a clear model of how releases to production work, as well as find paths to how to verify productions modified state and investigate new behavior (metrics, logs etc)

**Comment by andrewhowdencom** [comment]
Write pipelines for consumption by people who did not write the pipelines; it should be clear.

**Comment by andrew-howden** [comment]
Help tasks when the build fails

**Comment by andrew-howden** [comment]
Build images with few dependencies
