### ISSUE TITLE
As an organisational policy maker I want to know more about how to use (behavioural) economics to set organisational strategy

### ISSUE THREAD

**Issue by andrewhowdencom** [littlemanco/www.littleman.co#42]
Examples include:

- Production outages affecting the same person every time
- No technical debt being fixed
- Features being pushed down the pipe without justification

**Comment by andrewhowdencom** [comment]
https://twitter.com/maascamp/status/910338918234644482

**Comment by andrew-howden** [comment]
Each team optimizing for its own happiness over the happiness of the company.

**Comment by andrew-howden** [comment]
Completed in: https://www.littleman.co/articles/the-economics-of-software-development/

More is going to require more depth on the topic.
